user/models.py
from mongoengine import signals
from flask import url_for
import os

from application import db
from utilities.common import utc_timestamp as now
from settings import STATIC_IMAGE_URL, AWS_BUCKET, AWS_CONTENT_URL


class User(db.Document):
    #db_field is the name of the field in the actual document 
    #db_field converts all the username field to u which saves a lot of memory
    #in the database
    username= db.StringField(db_field="u", required=True, unique=True)
    password = db.StringField(db_field="p", required=True)
    email=db.EmailField(db_field="e", required=True, unique=True)
    first_name=db.StringField(db_field="fn", max_length=50)
    last_name=db.StringField(db_field="ln", max_length=50)
    created=db.IntField(db_field="c", default=now()) #don't store dates but store timestamp in UTC
    bio=db.StringField(db_field='b', max_length=160)
    email_confirmed=db.BooleanField(db_field="ecf", default=False)
    change_configuration=db.DictField(db_field="cc")  #stores json dictionary which contails old email to new email
    profile_image = db.StringField(db_field="i", default=None)
    
    @classmethod
    def pre_save(cls, sender, document, **kwargs):
        document.username = document.username.lower()
        document.email = document.email.lower()
    
    def profile_imgsrc(self, size):
        ''' this method fetches user's image url'''
        if self.profile_image:
            if AWS_BUCKET:
                return os.path.join(AWS_CONTENT_URL, AWS_BUCKET, 'user', '%s.%s.%s.png' % (self.id, self.profile_image, size))
            else:
                return url_for('static', filename=os.path.join(STATIC_IMAGE_URL, 'user', '%s.%s.%s.png' % (self.id, self.profile_image, size)))
        else:
            return url_for('static', filename=os.path.join(STATIC_IMAGE_URL, 'user', 'no-profile.%s.png' % (size)))
            
        
        
        
    meta={
        'indexes': ['username', 'email', '-created']
    }    
    
signals.pre_save.connect(User.pre_save, sender=User)
    
    
    
    
    

relationship/views.py
from flask import Blueprint, abort, session, redirect, url_for, request

from user.models import User
from relationship.models import Relationship
from user.decorators import login_required

relationship_app = Blueprint('relationship_app', __name__)

@relationship_app.route('/add_friend/<to_username>')
@login_required  #a user who isn't logged can't access this functionality
def add_friend(to_username):
    ref=request.referrer
    logged_user = User.objects.filter(username=session.get('username')).first() #get logged user
    to_user = User.objects.filter(username=to_username).first() #get username of a user we want to friend
    
    if to_user:
        rel = Relationship.get_relationship(logged_user, to_user) #get relationship between these two
        to_username= to_user.username
        #if rel == "FRIENDS_PENDING": #aleady requested
         #   return rel
        #elif rel == "BLOCKED":
         #   return rel
        #elif rel == "FRIENDS_APPROVED":
         #   return rel
        if rel == "REVERSE_FRIENDS_PENDING": #this person has already requested a logged in user a friendship
            Relationship(    #approve relationship to friends 
                from_user=logged_user,
                to_user=to_user,
                rel_type=Relationship.FRIENDS,
                status=Relationship.APPROVED
                ).save()
            reverse_rel = Relationship.objects.get(
                from_user=to_user,
                to_user=logged_user)
            reverse_rel.status=Relationship.APPROVED
            reverse_rel.save()
     
        elif rel == None and rel != "REVERSE_BLOCKED":   #if there is no relationship between two
        #if they didn't block each other
            Relationship(
                from_user=logged_user,
                to_user=to_user,
                rel_type=Relationship.FRIENDS,
                status=Relationship.PENDING
                ).save()
        return redirect(url_for('user_app.profile', username=to_username))
    
    else:
        abort(404)
        

@relationship_app.route('/remove_friend/<to_username>')
@login_required
def remove_friend(to_username):
    logged_user = User.objects.filter(username=session.get('username')).first()
    to_user = User.objects.filter(username=to_username).first()
    
    if to_user:
        rel = Relationship.get_relationship(logged_user, to_user)
        to_username = to_user.username
        if rel == "FRIENDS_PENDING" or rel == "FRIENDS_APPROVED" or rel == "REVERSE_FRIENDS_PENDING":
            rel = Relationship.objects.filter(
                from_user=logged_user,
                to_user=to_user).delete()
            reverse_rel = Relationship.objects.filter(
                from_user=to_user,
                to_user=logged_user).delete()
        return redirect(url_for('user_app.profile', username=to_username))
    else:
        abort(404)
        
        
        
@relationship_app.route('/block/<to_username>')
@login_required
def block(to_username):
    logged_user = User.objects.filter(username=session.get('username')).first()
    to_user = User.objects.filter(username=to_username).first()
    
    if to_user:
        rel = Relationship.get_relationship(logged_user, to_user)
        to_username = to_user.username
        
        if rel == "FRIENDS_PENDING" or rel == "FRIENDS_APPROVED" or rel == "REVERSE_FRIENDS_PENDING":
            rel = Relationship.objects.filter(
                from_user=logged_user,
                to_user=to_user).delete()
            reverse_rel = Relationship.objects.filter(
                from_user=to_user,
                to_user=logged_user).delete()
        Relationship(
            from_user=logged_user,
            to_user=to_user,
            rel_type=Relationship.BLOCKED,
            status=Relationship.APPROVED
            ).save()
        return redirect(url_for('user_app.profile', username=to_username))
    else:
        abort(404)
        
@relationship_app.route('/unblock/<to_username>')
@login_required
def unblock(to_username):
    logged_user = User.objects.filter(username=session.get('username')).first()
    to_user = User.objects.filter(username=to_username).first()
    
    if to_user:
        rel = Relationship.get_relationship(logged_user, to_user)
        to_username = to_user.username
        
        if rel == "BLOCKED":
            rel = Relationship.objects.filter(
                from_user=logged_user,
                to_user=to_user).delete()
        return redirect(url_for('user_app.profile', username=to_username))
    else:
        abort(404)

user/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for, abort
import bcrypt
import uuid 
import os
from werkzeug import secure_filename #stops malicious javascript other injections on the form

from user.models import User
from user.forms import RegisterForm, LoginForm, EditForm, ForgotForm, PasswordResetForm
from utilities.common import email
from settings import UPLOAD_FOLDER
from utilities.imaging import thumbnail_process
from relationship.models import Relationship
from user.decorators import login_required


user_app = Blueprint('user_app', __name__)
    
@user_app.route('/')
def index():
    return render_template("index.html")
    
@user_app.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        code = str(uuid.uuid4()) #generate random unique id that is used for confirmation code when email are sent to a registerred user
        
        user = User(
            username=form.username.data,
            password=hashed_password,
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            change_configuration = {"new_email": form.email.data.lower(), "confirmation_code": code}
            )
        #emailing the user
        body_html = render_template('mail/user/register.html', user=user)
        body_text = render_template('mail/user/register.txt', user=user)
        email(user.email, "Welcome to WorldChat", body_html, body_text)
        
        user.save()
        return "User registered"
    return render_template('user/register.html', form=form)
    
@user_app.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None
    
    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next')
        
    if form.validate_on_submit():
        user = User.objects.filter(
            username=form.username.data
            ).first()
        if user:
            if bcrypt.hashpw(form.password.data, user.password) == user.password:
                session['username'] = form.username.data
                if 'next' in session:
                    next = session.get('next')
                    session.pop('next')
                    return redirect(next)
                else:
                    return "User logged in"
            else:
                user = None
        if not user:
            error = 'Incorrect credentials'
    return render_template('user/login.html', form=form, error=error)
    
@user_app.route('/logout', methods=('GET', 'POST'))
def logout():
    session.pop('username')
    return redirect(url_for('user_app.login'))
    
@user_app.route('/<username>/friends/<int:page>')  #route for pagination
@user_app.route('/<username>/friends', endpoint='profile-friends')    
@user_app.route('/<username>')
def profile(username, page=1):
    friends_page=False
    logged_user=None
    rel=None
    edit_profile=False #if user is lookin at itself this path should be true
    user = User.objects.filter(username=username).first() #if username exist in the database
    if user:
        if session.get('username'): #if use is logged in
            logged_user = User.objects.filter(username=session.get('username')).first()
            rel = Relationship.get_relationship(logged_user, user)
            
        if session.get('username') and user.username == session.get('username'): #if user is looking at his own profile
            edit_profile=True
        
        
        
        # get friends
        friends = Relationship.objects.filter(
            from_user=user,
            rel_type=Relationship.FRIENDS,
            status=Relationship.APPROVED
            )
        friends_total = friends.count()
        
        
    
        if 'friends' in request.url:
            friends_page = True
            #paginate is mongoengine helper; 
            friends = friends.paginate(page=page, per_page=3) #page passed into url
        else:
            friends = friends[:5] #first five
        
        return render_template('user/profile.html', 
            user=user, 
            logged_user=logged_user,
            rel=rel, 
            edit_profile=edit_profile,
            friends=friends,
            friends_total=friends_total,
            friends_page=friends_page
            )
    else:
        abort(404)



@user_app.route('/edit', methods=('GET', 'POST'))
@login_required
def edit():
    error = None
    message = None
    user = User.objects.filter(username=session.get('username')).first()
    if user:
        form = EditForm(obj=user)
        if form.validate_on_submit():
            # check if image
            image_ts = None
            #if there's an image attached to the form , you check it:
            if request.files.get('image'): #check if user uploaded a file
                #get the file user uploaded on the form 
                filename = secure_filename(form.image.data.filename) 
                file_path = os.path.join(UPLOAD_FOLDER, 'user', filename)
                form.image.data.save(file_path) #save it on the file path: static/img/user
                image_ts = str(thumbnail_process(file_path, 'user', str(user.id))) #generate a timestamp for the uploaded file
                #at the end if no error, store this timestamp in the database
            
                
            if user.username != form.username.data.lower():
                if User.objects.filter(username=form.username.data.lower()).first():
                    error = "Username already exists"
                else:
                    session['username'] = form.username.data.lower()
                    form.username.data = form.username.data.lower()
            if user.email != form.email.data.lower():
                if User.objects.filter(email=form.email.data.lower()).first():
                    error = "Email already exists"
                else:
                    code = str(uuid.uuid4())
                    
                    user.change_configuration = {
                        "new_email": form.email.data.lower(),
                        "confirmation_code": code
                    }
                    user.email_confirmed = False
                    form.email.data = user.email
                    message = "You will need to confirm the new email to complete this change"
                    
                    # email the user
                    body_html = render_template('mail/user/change_email.html', user=user)
                    body_text = render_template('mail/user/change_email.txt', user=user)
                    email(user.change_configuration['new_email'], "Confirm your new email", body_html, body_text)
                    
            if not error:
                form.populate_obj(user)
                if image_ts:
                    user.profile_image = image_ts   #save image into database
                    #after it saves, 4 images(raw, lg, xlg, sm) show up in static/img/user folder for a user 
                user.save()
                
                if not message:
                    message = "Profile updated"
                    
    
        return render_template("user/edit.html", form=form, error=error, message=message, user=user)
    else:
        abort(404)
@user_app.route('/confirm/<username>/<code>', methods=('GET', 'POST'))
def confirm(username, code):
    user = User.objects.filter(username=username).first()
    if user and user.change_configuration and user.change_configuration.get('confirmation_code'):
        if code == user.change_configuration.get('confirmation_code'):
            user.email = user.change_configuration.get('new_email')
            user.change_configuration = {}
            user.email_confirmed = True
            user.save()
            return render_template('user/email_confirmed.html')
    else:
        abort(404)

@user_app.route('/forgot', methods=('GET', 'POST'))
def forgot():
    error = None
    message = None
    form = ForgotForm()
    if form.validate_on_submit():
        user = User.objects.filter(email=form.email.data.lower()).first()
        if user:
            code = str(uuid.uuid4())
            user.change_configuration={
                "password_reset_code": code
            }
            user.save()
            
            # email the user
            body_html = render_template('mail/user/password_reset.html', user=user)
            body_text = render_template('mail/user/password_reset.txt', user=user)
            email(user.email, "Password reset request", body_html, body_text)
            
        message = "You will receive a password reset email if we find that email in our system"
    return render_template('user/forgot.html', form=form, error=error, message=message)

@user_app.route('/password_reset/<username>/<code>', methods=('GET', 'POST'))
def password_reset(username, code):
    message = None
    require_current = None
    
    form = PasswordResetForm()
    
    user = User.objects.filter(username=username).first()
    if not user or code != user.change_configuration.get('password_reset_code'):
        abort(404)
        
    if request.method == 'POST':
        del form.current_password
        if form.validate_on_submit():
            salt = bcrypt.gensalt()
            hashed_password = bcrypt.hashpw(form.password.data, salt)
            user.password = hashed_password
            user.change_configuration = {}
            user.save()
            
            if session.get('username'):
                session.pop('username')
            return redirect(url_for('user_app.password_reset_complete'))
            
    return render_template('user/password_reset.html',
        form=form,
        message=message,
        require_current=require_current,

templates/user/edit.html
{% extends "base.html" %}

{% block title %}Edit profile{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Edit Profile</h3>
    
    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}

    {% if message %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endif %}
    
    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.edit')}}" role="form"  enctype="multipart/form-data">
     <!-- enctype is used as a separator of actual form and an image file as an attachment -->
      {{ form.hidden_tag() }}
      
      
      <!-- when user upload a picture is shows it in the edit form -->
       {% if user.profile_image %}
      <div class="thumbnail">
        <!--
        <img src="{{ url_for('static', filename=user.profile_imgsrc('xlg')) }}" class="img-rounded">
        -->
      
       <img src="{{ user.profile_imgsrc('xlg') }}" class="img-rounded">
      
      </div>
      {% endif %}
      
      <!-- rendering the image edit field -->
       {{ render_field(form.image, class='form-control') }}

      {{ render_field(form.first_name, class='form-control') }}
      {{ render_field(form.last_name, class='form-control') }}
      
      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.email, class='form-control') }}

      {{ render_field(form.bio, maxlength="160", rows="3", class='form-control') }}

      <button type="submit" class="btn btn-default">Save</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/email_confirmed.html
{% extends "base.html" %}

{% block title %}Email confirmed{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">
    
    <div class="well well-lg">Your email has been confirmed</div>
    
  </div>

</div>

{% endblock %}

templates/user/forgot.html
{% extends "base.html" %}

{% block title %}Forgot password{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">
    
    <h3>Forgot password</h3>
    
    <p>Please enter your email address and we will send a password reset link to your email.</p>

    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}
    
    {% if message %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.forgot')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.email, class='form-control') }}

      <button type="submit" class="btn btn-default">Reset password</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">
    
    <h3>User Login</h3>

    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.login')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.password, **{"class": "form-control", "aria-described-by": "passwordHelpBlock"}) }}
      
      <span id="passwordHelpBlock" class="help-block"><a href="{{ url_for('.forgot') }}">Forgot password?</a></span>

      <button type="submit" class="btn btn-default">Login</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/password_change_confirmed.html
{% extends "base.html" %}

{% block title %}Password change confirmed{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">
    
    <div class="well well-lg">Your password has been updated. Please <a href="{{ url_for('user_app.login') }}">login</a> using your new passwword.</div>
    
  </div>

</div>

{% endblock %}

templates/user/profile.html
{% extends "base.html" %} 

{% block title %}{{ user.username }} - Profile{% endblock %} 

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %} 

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-3">

    <img class="img-thumbnail" src="{{ user.profile_imgsrc('xlg') }}" width="200" height="200" alt="{{ user.username }}">

    <h3 class="profile-fullname">{{ user.first_name }} {{ user.last_name }}</h3>
    <h3 class="profile-username"><a href="{{ url_for('user_app.profile', username=user.username) }}" />@{{ user.username }}</a></h3>

  </div> <!-- col-md-3 -->
  
  <div id="friends-toolbar" class="row">
  
      <div class="btn-toolbar pull-right" role="toolbar" aria-label="friends-toolbar"> <!-- btn toolbar opening -->
        <div class="btn-group" role="group" aria-label="friends-toolbar-buttons"> <!-- btn group -->
          {% if edit_profile %}
          <a href="{{ url_for('.edit') }}" role="button" class="btn btn-default">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            Edit profile
          </a>
          {% else %}
          
             {% if rel == None %}
            <a href="{{ url_for('relationship_app.add_friend', to_username=user.username) }}" role="button" class="btn btn-default">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Friend
            </a>  
            <a href="{{ url_for('relationship_app.block', to_username=user.username) }}" role="button" class="btn btn-default">
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Block
            </a>   
            {% endif %}
            
             {% if rel == "BLOCKED" %}
            <a href="{{ url_for('relationship_app.unblock', to_username=user.username) }}" role="button" id="relationship-blocked" class="btn btn-danger">
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <span id="relationship-label">Blocked</span>
            </a>
            {% endif %}
            
      
            
            
             {% if rel == "FRIENDS_APPROVED" %}
            <a href="{{ url_for('relationship_app.remove_friend', to_username=user.username) }}" role="button" id="relationship-friends" class="btn btn-primary">
              <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> <span id="relationship-label">Friends</span>
            </a>
            {% endif %}

            {% if rel == "FRIENDS_PENDING" %}
            <a href="{{ url_for('relationship_app.remove_friend', to_username=user.username) }}" role="button" id="relationship-friends-requested" class="btn btn-primary">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span id="relationship-label">Friendship Requested</span>
            </a>
            {% endif %}

            {% if rel == "REVERSE_FRIENDS_PENDING" %}
            <a href="{{ url_for('relationship_app.add_friend', to_username=user.username) }}" role="button" id="relationship-reverse-friends-requested" class="btn btn-primary">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span id="relationship-label">Accept Friendship</span>
            </a>
            <a href="{{ url_for('relationship_app.remove_friend', to_username=user.username) }}" role="button" id="relationship-reverse-friends-cancel" class="btn btn-default">
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <span id="relationship-label">Deny Friendship</span>
            </a>            
            {% endif %}
            
            
            <!-- this is just for testing: to test if reverse-bloked is working -->
          {% if rel == "REVERSE_BLOCKED" %}
              <a href="#" id="relationship-reverse-blocked"></a>
            {% endif %}   
          
        
          {% endif %}
        </div> <!-- btn group closing-->
      </div> <!-- btn toolbar closing --> 
      
    </div> <!-- friends-toolbar -->
    
    <div class="row">
      {% if not friends_page %}
      <div class="col-md-9">
        
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50" alt="{{ user.username }}">
            </a>
          </div>
          <div class="media-body">
            <p>Fotima Atabaeva <a href="#">@moonstar</a><br />
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non massa ut ante interdum sagittis. Quisque eu sapien enim. Phasellus sit amet viverra massa, sit amet rhoncus dui. Nam tortor justo, finibus ut gravida et, accumsan ac sapien. Integer nec commodo libero. Nam auctor vestibulum congue. Donec convallis mollis lorem, eu mattis sem luctus in. Curabitur tincidunt odio sit amet nulla fringilla, vel gravida orci aliquam. Donec viverra mollis tortor, a suscipit risus molestie at. Sed ut tincidunt metus. Maecenas nec dignissim velit, eget placerat lectus.
            </p>
          </div>
        </div> <!-- media -->
        
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="//placehold.it/50x50" width="50" heigh="50" alt="{{ user.username }}">
            </a>
          </div>
          <div class="media-body">
            <p>Fotima Atabaeva <a href="#">@moonstar</a><br />
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non massa ut ante interdum sagittis. Quisque eu sapien enim. Phasellus sit amet viverra massa, sit amet rhoncus dui. Nam tortor justo, finibus ut gravida et, accumsan ac sapien. Integer nec commodo libero. Nam auctor vestibulum congue. Donec convallis mollis lorem, eu mattis sem luctus in. Curabitur tincidunt odio sit amet nulla fringilla, vel gravida orci aliquam. Donec viverra mollis tortor, a suscipit risus molestie at. Sed ut tincidunt metus. Maecenas nec dignissim velit, eget placerat lectus.
            </p>
          </div>
        </div> <!-- media -->
        
      </div> <!-- col-md-9 -->
    
      <div class="col-md-3">  <!-- friends sidebar-->

         <h4><span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
          <a href="{{ url_for('.profile-friends', username=user.username) }}">Friends</a>
        <span class="badge">{{ friends_total }}</span></h4>
        {% for friend in friends %}
        <div class="media">
          <div class="media-left">
            <a class="img-thumnbnail" href="{{ url_for('.profile', username=friend.to_user.username) }}">
              <img class="media-object" src="{{ friend.to_user.profile_imgsrc('sm') }}" width="50" height="50" alt="{{ friend.to_user.username }}">
            </a>
          </div>
          <div class="media-body">
            <p>{{ friend.to_user.first_name }}<br />
              <a href="{{ url_for('.profile', username=friend.to_user.username) }}">@{{ friend.to_user.username }}</a>
            </p>
          </div>
        </div> <!-- media -->
      {% endfor %}
       
      </div> <!-- col-md-3 --> <!-- friend's sidebar -->
      
       {% else %}
      
      <div class="col-md-12"> <!-- == Friend list == -->
      
        <div class="row">
          
          {% for friend in friends.items %}
          
            <div class="col-md-3">
              <div class="friend-grid-user-image">
                <a class="img-thumbnail" href="{{ url_for('.profile', username=friend.to_user.username) }}">
                  <img src="{{ friend.to_user.profile_imgsrc('lg') }}" width="75" alt="{{ friend.to_user.username }}">
                </a>
              </div>
              <div class="friend-grid-user-data">
                <h4 class="profile-fullname">{{ friend.to_user.first_name }} {{ friend.to_user.last_name }} </h5>
                <h5 class="profile-username"><a href="{{ url_for('.profile', username=friend.to_user.username) }}">@{{ friend.to_user.username }}</a></h4>
              </div>
              <div class="friend-grid-user-friends-button">
                {{ friend.is_friend(logged_user) }}
              </div>
            </div> <!-- col-md-3 -->
            
          {% endfor %}
          
        </div> <!-- row -->
      
      </div>
      
      {% endif %}
      
      
    </div> <!-- row -->
    
  </div> <!-- col-md-9 -->

</div>
{% endblock %}


{% block end_body_js %}
<script type="text/javascript">
$(document).ready(function(){
  $('#relationship-friends').mouseover(function() {
    $(this).find('#relationship-label').text('Unfriend');
    $(this).attr("class", "btn btn-default");
  }).mouseout(function(){
    $(this).find('#relationship-label').text('Friends');
    $(this).attr("class", "btn btn-primary");
  });            
});
$(document).ready(function(){
  $('#relationship-blocked').mouseover(function() {
    $(this).find('#relationship-label').text('Unblock');
    $(this).attr("class", "btn btn-default");
  }).mouseout(function(){
    $(this).find('#relationship-label').text('Blocked');
    $(this).attr("class", "btn btn-danger");
  });            
});
$(document).ready(function(){
  $('#relationship-friends-requested').mouseover(function() {
    $(this).find('#relationship-label').text('Cancel Friend Request');
    $(this).attr("class", "btn btn-danger");
  }).mouseout(function(){
    $(this).find('#relationship-label').text('Friendship Requested');
    $(this).attr("class", "btn btn-primary");
  });            
});
</script>
{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Registration</h3>

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('user_app.register')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.first_name, class='form-control') }}
      {{ render_field(form.last_name, class='form-control') }}
      
      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.email, class='form-control') }}
      
      {{ render_field(form.password, class='form-control') }}
      {{ render_field(form.confirm, class='form-control') }}

      <button type="submit" class="btn btn-default">Register</button>

    </form>

  </div>

</div>
{% endblock %}